name: 02 - Events

on: 
  workflow_dispatch:
      

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "This event is triggered by ${{ github.event_name }}"