name: 05-input-output

on: 
  workflow_dispatch:
    inputs:
      status:
        description: To perform deploy stages or not
        type: choice
        options:
          - success
          - fail

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      live-is: ${{steps.build.outputs.live}}
    steps:
      - name: Print input
        id: build
        run: |
          echo "${{ inputs.status }}"
          echo "live=true" >> $GITHUB_OUTPUT
      - name: Deploy Stage
        if: ${{ inputs.status == success }}
        run: |
          echo "Deployment done"
          echo "${{ output.live }}"
        

        
